In [1]:
import sys
sys.path.append('../')
from src.core.scraper.app import ScrapingUtils
from bs4 import BeautifulSoup
from src.core.scraper.generic_extractor import GenericExtractor
generic_extractor = GenericExtractor()
scraper_utils = ScrapingUtils()

In [2]:
# input_urls = [
#     "https://www.italika.mx/motos/motocicletas/motoneta",
#     "https://www.italika.mx/motos/motocicletas/cuatrimotos",
#     "https://www.italika.mx/motos/motocicletas/urbanas",
#     "https://www.italika.mx/motos/motocicletas/trabajo",
#     "https://www.italika.mx/motos/motocicletas/vort-x",
#     "https://www.italika.mx/motos/motocicletas/chopper",
#     "https://www.italika.mx/motos/motocicletas/doble-proposito",
#     "https://www.italika.mx/motos/motocicletas/cafe-racer",
#     "https://www.italika.mx/motos/motocicletas/morbidelli",
#     "https://www.italika.mx/motos/motocicletas/deportiva",]

In [3]:
# italika_links = []
# for url in input_urls:
#     response = scraper_utils.get_content_from_website(url, formats=["html"])
#     html = response.html
#     soup = BeautifulSoup(html, "html.parser")
#     links = [a.get('href') for a in soup.find_all("a")]
#     for link in links:
#         if "italika-" in link and "cadena" not in link:
#             italika_links.append(link)

In [4]:
# import requests

# def check_url_ok(url):
#     try:
#         # Allow redirects but track them
#         resp = requests.get(url, timeout=10, allow_redirects=True)
#         # If any redirect happened, ignore this page (fail it)
#         if len(resp.history) > 0:
#             return False
#         if resp.status_code == 200:
#             soup = BeautifulSoup(resp.text, "html.parser")
#             h1 = soup.find("h1")
#             if h1 and ("Lo sentimos" in h1.get_text()):
#                 return False
#             return True
#         else:
#             return False
#     except Exception as e:
#         return False

# italika_ok = []
# italika_fail = []

# for link in italika_links:
#     full_url = link if link.startswith("http") else f"https://www.italika.mx{link}"
#     if check_url_ok(full_url):
#         italika_ok.append(full_url)
#     else:
#         italika_fail.append(full_url)

In [5]:
italika_ok = ['https://www.italika.mx/motoneta-italika-d150-lt-negra-34005388/p',
 'https://www.italika.mx/motoneta-italika-ws150-sport-marino-34006551/p',
 'https://www.italika.mx/motoneta-italika-ws175-sport-grafito-34006561/p',
 'https://www.italika.mx/motoneta-italika-vitalia-150-beige-con-gps-34006773/p',
 'https://www.italika.mx/motoneta-italika-d150-blanco-con-azul-34006669/p',
 'https://www.italika.mx/motoneta-italika-modena-175-con-gps-azul-34006716/p',
 'https://www.italika.mx/motoneta-italika-bit-150-blanca-con-negro-34006931/p',
 'https://www.italika.mx/motoneta-italika-d125-azul-con-negro-34006289/p',
 'https://www.italika.mx/motoneta-italika-ds150-negra-34006307/p',
 'https://www.italika.mx/cuatrimoto-italika-atv300-azul-34006717/p',
 'https://www.italika.mx/cuatrimoto-italika-atv200-naranja-34006718/p',
 'https://www.italika.mx/cuatrimoto-italika-atv-190-gris-34006332/p',
 'https://www.italika.mx/motocicleta-urbana-italika-280z-gris-34006326/p',
 'https://www.italika.mx/motocicleta-italika-250z-carbono-negra-con-gps-34007058/p',
 'https://www.italika.mx/motocicleta-italika-200z-azul-con-gps-34006885/p',
 'https://www.italika.mx/motocicleta-italika-150z-negra-con-azul-con-gps-34007056/p',
 'https://www.italika.mx/motocicleta-urbana-italika-125z-gris-con-negro-con-gps-34007055/p',
 'https://www.italika.mx/motocicleta-de-trabajo-italika-at125-grafito-34006712/p',
 'https://www.italika.mx/motocicleta-de-trabajo-italika-ft125-ts-roja-con-negro-34005164/p',
 'https://www.italika.mx/motocicleta-de-trabajo-italika-at110-rt-azul-34006720/p',
 'https://www.italika.mx/motocicleta-de-trabajo-italika-ft200-negra-34006715/p',
 'https://www.italika.mx/motocicleta-de-trabajo-italika-ft150-roja-34006714/p',
 'https://www.italika.mx/motocicleta-de-trabajo-italika-ft150-ts-negro-con-verde-34005332/p',
 'https://www.italika.mx/motocicleta-de-trabajo-italika-at135x-verde-34006711/p',
 'https://www.italika.mx/motocicleta-de-trabajo-italika-ft250-gts-con-gps-azul-con-negro-34006392/p',
 'https://www.italika.mx/motocicleta-de-trabajo-italika-ft200-gts-gris-con-gps-34007052/p',
 'https://www.italika.mx/motocicleta-italika-ft150-gts-gris-con-amarillo-con-gps-34007053/p',
 'https://www.italika.mx/motocicleta-de-trabajo-italika-at130-rt-blanca-34006713/p',
 'https://www.italika.mx/motocicleta-de-trabajo-italika-ft125-negra-34005157/p',
 'https://www.italika.mx/motocicleta-deportiva-italika-vort-x-300r-azul-con-gris-34006484/p',
 'https://www.italika.mx/motocicleta-deportiva-italika-vort-x-250-roja-con-negro-34005120/p',
 'https://www.italika.mx/motocicleta-deportiva-italika-vort-x-300-roja-con-negro-34004912/p',
 'https://www.italika.mx/motocicleta-chopper-italika-rc200-gris-34005722/p',
 'https://www.italika.mx/motocicleta-chopper-italika-tc-250-gris-34006691/p',
 'https://www.italika.mx/motocicleta-chopper-italika-rc250-negra-34005813/p',
 'https://www.italika.mx/motocicleta-chopper-italika-tc-300-negra-34006362/p',
 'https://www.italika.mx/motocicleta-doble-proposito-italika-dm150-con-gps-blanca-34006888/p',
 'https://www.italika.mx/motocicleta-italika-dm300-dorado-con-gps-34006890/p',
 'https://www.italika.mx/motocicleta-doble-proposito-italika-dm200-con-gps-azul-34006255-1300703478/p',
 'https://www.italika.mx/motocicleta-italika-firebird-300-negra-con-gps-34007122/p',
 'https://www.italika.mx/motocicleta-cafe-racer-italika-sptfire-250-plata-34005271/p',
 'https://www.italika.mx/motocicleta-italika-morbidelli-f200-34006932/p',
 'https://www.italika.mx/motocicleta-italika-morbidelli-nz250-34006882/p',
 'https://www.italika.mx/motocicleta-italika-morbidelli-t250x-gris-34007161/p',
 'https://www.italika.mx/motocicleta-deportiva-italika-rt-250-con-gps-roja-34007114/p']

In [6]:
response, content = generic_extractor.get_model_data('https://www.italika.mx/motocicleta-italika-morbidelli-f200-34006932/p')

In [9]:
print(content.metadata)

title='Motocicleta Italika-Morbidelli F200' description='Motocicleta Italika-Morbidelli F200 | Encuentra todos tus productos favoritos | Con tu crédito compra fácil y rápido desde tu hogar' url='https://www.italika.mx/motocicleta-italika-morbidelli-f200-34006932/p' language='es-MX, es-MX' keywords=None robots='index, follow' og_title='Motocicleta Italika-Morbidelli F200 - Tienda Motos Italika Mexico' og_description='Motocicleta Italika-Morbidelli F200 | Encuentra todos tus productos favoritos | Con tu crédito compra fácil y rápido desde tu hogar' og_url='https://www.italika.mx/motocicleta-italika-morbidelli-f200-34006932/p' og_image='https://elektra.vtexassets.com/arquivos/ids/24220254/34006932.jpg?v=639083338930930000' og_audio=None og_determiner=None og_locale=None og_locale_alternate=None og_site_name=None og_video=None favicon='https://www.italika.mx/arquivos/LOGO-ITK.png' dc_terms_created=None dc_date_created=None dc_date=None dc_terms_type=None dc_type=None dc_terms_audience=None dc_terms_subject=None dc_subject=None dc_description=None dc_terms_keywords=None modified_time=None published_time=None article_tag=None article_section=None source_url='https://www.italika.mx/motocicleta-italika-morbidelli-f200-34006932/p' status_code=200 scrape_id='019cc0fd-6083-73bf-9eab-4f4f42ab6e6c' num_pages=None content_type='text/html; charset=utf-8' proxy_used='basic' timezone='America/New_York' cache_state=None cached_at=None credits_used=5 concurrency_limited=False concurrency_queue_duration_ms=None error=None generator='vtex.render-server@8.179.1' product:retailer_part_no='1300893043' product:brand='MORBIDELLI' facebook-domain-verification='lyi7m2z3j5uet0uz1gqbnb092zrkbe' theme-color='#ffffff' apple-mobile-web-app-capable='yes' google-site-verification='44jEi0ho6RTHB9S1YKVdkF2ZAoKhJ8tRn8hzExVK6Ys' viewport=['width=device-width, initial-scale=1', 'width=device-width, initial-scale=1'] product:retailer_item_id='1300893043' currency='MXN' product:sku='34006932' copyright='Italika en Línea' product:price:amount='39999' author='Italika en Línea' Petal-Search-site-verification='bd0549c756' country='MEX' og:description='Motocicleta Italika-Morbidelli F200 | Encuentra todos tus productos favoritos | Con tu crédito compra fácil y rápido desde tu hogar' product:condition='new' product:price:currency='MXN' product:category=['/Motos/Motocicletas/Morbidelli/', '/Motos/Motocicletas/', '/Motos/'] product:availability='instock' og:title='Motocicleta Italika-Morbidelli F200 - Tienda Motos Italika Mexico' og:url='https://www.italika.mx/motocicleta-italika-morbidelli-f200-34006932/p' og:image=['https://elektra.vtexassets.com/arquivos/ids/24220254/34006932.jpg?v=639083338930930000', 'https://elektra.vtexassets.com/arquivos/ids/24220246/34006932-d1.jpg?v=639083338921770000', 'https://elektra.vtexassets.com/arquivos/ids/24220247/34006932-d3.jpg?v=639083338923800000'] og:type='product' storefront='store_framework'

In [7]:
print(response)

base_price=62999.0 net_price=39999.0 discount_amount=23000.0 model='F200' colors=[]

In [7]:
import pandas as pd

model_data_list = []
failed_urls = []
processed_urls = []
for idx, url in enumerate(italika_ok):
    print(f"[{idx+1}/{len(italika_ok)}] Procesando: {url}")
    response = generic_extractor.get_model_data(url)
    if response is not None:
        data_dict = response.model_dump() if hasattr(response, 'model_dump') else response.__dict__
        data_dict['url'] = url
        model_data_list.append(data_dict)
        print(f"  ✓ Información extraída correctamente.")
        processed_urls.append(url)
    else:
        print(f"  ✗ No se pudo extraer información. Se añadirá a la lista de pendientes.")
        failed_urls.append(url)
        # NO volvemos a scrapear, solo guardamos los nulls para revisar después
        model_data_list.append({
            "base_price": None,
            "net_price": None,
            "discount_amount": None,
            "model": None,
            "colors": None,
            "sku": None,
            "url": url
        })

print("\n--- URLs que fallaron y necesitan revisión manual o reintento: ---")
for u in failed_urls:
    print(u)

[1/45] Procesando: https://www.italika.mx/motoneta-italika-d150-lt-negra-34005388/p
  ✓ Información extraída correctamente.
[2/45] Procesando: https://www.italika.mx/motoneta-italika-ws150-sport-marino-34006551/p
  ✓ Información extraída correctamente.
[3/45] Procesando: https://www.italika.mx/motoneta-italika-ws175-sport-grafito-34006561/p
  ✓ Información extraída correctamente.
[4/45] Procesando: https://www.italika.mx/motoneta-italika-vitalia-150-beige-con-gps-34006773/p
  ✓ Información extraída correctamente.
[5/45] Procesando: https://www.italika.mx/motoneta-italika-d150-blanco-con-azul-34006669/p
  ✓ Información extraída correctamente.
[6/45] Procesando: https://www.italika.mx/motoneta-italika-modena-175-con-gps-azul-34006716/p
  ✓ Información extraída correctamente.
[7/45] Procesando: https://www.italika.mx/motoneta-italika-bit-150-blanca-con-negro-34006931/p
  ✓ Información extraída correctamente.
[8/45] Procesando: https://www.italika.mx/motoneta-italika-d125-azul-con-negro-34006289/p
  ✓ Información extraída correctamente.
[9/45] Procesando: https://www.italika.mx/motoneta-italika-ds150-negra-34006307/p
  ✓ Información extraída correctamente.
[10/45] Procesando: https://www.italika.mx/cuatrimoto-italika-atv300-azul-34006717/p
  ✓ Información extraída correctamente.
[11/45] Procesando: https://www.italika.mx/cuatrimoto-italika-atv200-naranja-34006718/p
  ✓ Información extraída correctamente.
[12/45] Procesando: https://www.italika.mx/cuatrimoto-italika-atv-190-gris-34006332/p
  ✓ Información extraída correctamente.
[13/45] Procesando: https://www.italika.mx/motocicleta-urbana-italika-280z-gris-34006326/p
  ✓ Información extraída correctamente.
[14/45] Procesando: https://www.italika.mx/motocicleta-italika-250z-carbono-negra-con-gps-34007058/p
  ✓ Información extraída correctamente.
[15/45] Procesando: https://www.italika.mx/motocicleta-italika-200z-azul-con-gps-34006885/p
  ✓ Información extraída correctamente.
[16/45] Procesando: https://www.italika.mx/motocicleta-italika-150z-negra-con-azul-con-gps-34007056/p
  ✓ Información extraída correctamente.
[17/45] Procesando: https://www.italika.mx/motocicleta-urbana-italika-125z-gris-con-negro-con-gps-34007055/p
  ✓ Información extraída correctamente.
[18/45] Procesando: https://www.italika.mx/motocicleta-de-trabajo-italika-at125-grafito-34006712/p
  ✓ Información extraída correctamente.
[19/45] Procesando: https://www.italika.mx/motocicleta-de-trabajo-italika-ft125-ts-roja-con-negro-34005164/p
  ✓ Información extraída correctamente.
[20/45] Procesando: https://www.italika.mx/motocicleta-de-trabajo-italika-at110-rt-azul-34006720/p
  ✓ Información extraída correctamente.
[21/45] Procesando: https://www.italika.mx/motocicleta-de-trabajo-italika-ft200-negra-34006715/p
  ✓ Información extraída correctamente.
[22/45] Procesando: https://www.italika.mx/motocicleta-de-trabajo-italika-ft150-roja-34006714/p
  ✓ Información extraída correctamente.
[23/45] Procesando: https://www.italika.mx/motocicleta-de-trabajo-italika-ft150-ts-negro-con-verde-34005332/p
  ✓ Información extraída correctamente.
[24/45] Procesando: https://www.italika.mx/motocicleta-de-trabajo-italika-at135x-verde-34006711/p
  ✓ Información extraída correctamente.
[25/45] Procesando: https://www.italika.mx/motocicleta-de-trabajo-italika-ft250-gts-con-gps-azul-con-negro-34006392/p
  ✓ Información extraída correctamente.
[26/45] Procesando: https://www.italika.mx/motocicleta-de-trabajo-italika-ft200-gts-gris-con-gps-34007052/p
  ✓ Información extraída correctamente.
[27/45] Procesando: https://www.italika.mx/motocicleta-italika-ft150-gts-gris-con-amarillo-con-gps-34007053/p
  ✓ Información extraída correctamente.
[28/45] Procesando: https://www.italika.mx/motocicleta-de-trabajo-italika-at130-rt-blanca-34006713/p
  ✓ Información extraída correctamente.
[29/45] Procesando: https://www.italika.mx/motocicleta-de-trabajo-italika-ft125-negra-34005157/p
  ✓ Información extraída correctamente.
[30/45] Procesando: https://www.italika.mx/motocicleta-deportiva-italika-vort-x-300r-azul-con-gris-34006484/p
  ✓ Información extraída correctamente.
[31/45] Procesando: https://www.italika.mx/motocicleta-deportiva-italika-vort-x-250-roja-con-negro-34005120/p
  ✓ Información extraída correctamente.
[32/45] Procesando: https://www.italika.mx/motocicleta-deportiva-italika-vort-x-300-roja-con-negro-34004912/p
  ✓ Información extraída correctamente.
[33/45] Procesando: https://www.italika.mx/motocicleta-chopper-italika-rc200-gris-34005722/p
  ✓ Información extraída correctamente.
[34/45] Procesando: https://www.italika.mx/motocicleta-chopper-italika-tc-250-gris-34006691/p
  ✓ Información extraída correctamente.
[35/45] Procesando: https://www.italika.mx/motocicleta-chopper-italika-rc250-negra-34005813/p
  ✓ Información extraída correctamente.
[36/45] Procesando: https://www.italika.mx/motocicleta-chopper-italika-tc-300-negra-34006362/p
  ✓ Información extraída correctamente.
[37/45] Procesando: https://www.italika.mx/motocicleta-doble-proposito-italika-dm150-con-gps-blanca-34006888/p
  ✓ Información extraída correctamente.
[38/45] Procesando: https://www.italika.mx/motocicleta-italika-dm300-dorado-con-gps-34006890/p
  ✓ Información extraída correctamente.
[39/45] Procesando: https://www.italika.mx/motocicleta-doble-proposito-italika-dm200-con-gps-azul-34006255-1300703478/p
  ✓ Información extraída correctamente.
[40/45] Procesando: https://www.italika.mx/motocicleta-italika-firebird-300-negra-con-gps-34007122/p
  ✓ Información extraída correctamente.
[41/45] Procesando: https://www.italika.mx/motocicleta-cafe-racer-italika-sptfire-250-plata-34005271/p
  ✓ Información extraída correctamente.
[42/45] Procesando: https://www.italika.mx/motocicleta-italika-morbidelli-f200-34006932/p
  ✓ Información extraída correctamente.
[43/45] Procesando: https://www.italika.mx/motocicleta-italika-morbidelli-nz250-34006882/p
  ✓ Información extraída correctamente.
[44/45] Procesando: https://www.italika.mx/motocicleta-italika-morbidelli-t250x-gris-34007161/p
  ✓ Información extraída correctamente.
[45/45] Procesando: https://www.italika.mx/motocicleta-deportiva-italika-rt-250-con-gps-roja-34007114/p
  ✓ Información extraída correctamente.

--- URLs que fallaron y necesitan revisión manual o reintento: ---

In [8]:
df = pd.DataFrame(model_data_list)
df.head()  # Display the first rows of the resulting DataFrame

,base_price,net_price,discount_amount,model,colors,url
0,26999.0,18999.0,8000.0,D 150 LT,[Negro],https://www.italika.mx/motoneta-italika-d150-l...
1,34499.0,23999.0,10500.0,WS150 SPORT,[Azul],https://www.italika.mx/motoneta-italika-ws150-...
2,35999.0,25999.0,10000.0,WS175 SPORT,[Negro],https://www.italika.mx/motoneta-italika-ws175-...
3,40999.0,29999.0,11000.0,VITALIA 150,[Beige],https://www.italika.mx/motoneta-italika-vitali...
4,28999.0,21999.0,7000.0,D150,[Blanco],https://www.italika.mx/motoneta-italika-d150-b...

In [11]:
pd.set_option('display.max_colwidth', None)

In [18]:
column_order = ["model", "colors", "base_price", "discount_amount", "net_price", "url"]

In [19]:
df_models = df[df["model"].notna()][column_order]

In [15]:
df_models_null = df[df["model"].isna()]

In [20]:
df_models

,model,colors,base_price,discount_amount,net_price,url
0,D 150 LT,[Negro],26999.0,8000.0,18999.0,https://www.italika.mx/motoneta-italika-d150-lt-negra-34005388/p
1,WS150 SPORT,[Azul],34499.0,10500.0,23999.0,https://www.italika.mx/motoneta-italika-ws150-sport-marino-34006551/p
2,WS175 SPORT,[Negro],35999.0,10000.0,25999.0,https://www.italika.mx/motoneta-italika-ws175-sport-grafito-34006561/p
3,VITALIA 150,[Beige],40999.0,11000.0,29999.0,https://www.italika.mx/motoneta-italika-vitalia-150-beige-con-gps-34006773/p
4,D150,[Blanco],28999.0,7000.0,21999.0,https://www.italika.mx/motoneta-italika-d150-blanco-con-azul-34006669/p
5,MODENA 175,[Azul],35999.0,6000.0,29999.0,https://www.italika.mx/motoneta-italika-modena-175-con-gps-azul-34006716/p
6,BIT150,[Blanco],40499.0,13500.0,26999.0,https://www.italika.mx/motoneta-italika-bit-150-blanca-con-negro-34006931/p
7,D 125,[Azul],25999.0,9000.0,16999.0,https://www.italika.mx/motoneta-italika-d125-azul-con-negro-34006289/p
8,DS 150,[Naranja],35499.0,9500.0,25999.0,https://www.italika.mx/motoneta-italika-ds150-negra-34006307/p
9,ATV300,[Azul],92999.0,13000.0,79999.0,https://www.italika.mx/cuatrimoto-italika-atv300-azul-34006717/p
10,ATV200,[Naranja],62499.0,12500.0,49999.0,https://www.italika.mx/cuatrimoto-italika-atv200-naranja-34006718/p
11,TV190,[Gris],52999.0,8000.0,44999.0,https://www.italika.mx/cuatrimoto-italika-atv-190-gris-34006332/p
12,280Z,[Gris],65999.0,24000.0,41999.0,https://www.italika.mx/motocicleta-urbana-italika-280z-gris-34006326/p
13,250Z GPS,[Negro],57499.0,12500.0,44999.0,https://www.italika.mx/motocicleta-italika-250z-carbono-negra-con-gps-34007058/p
14,200Z GPS,[Azul],53999.0,16000.0,37999.0,https://www.italika.mx/motocicleta-italika-200z-azul-con-gps-34006885/p
15,MOTONETA,"[Rojo, Negro, Azul]",15000.0,1500.0,13500.0,https://www.italika.mx/motocicleta-italika-150z-negra-con-azul-con-gps-34007056/p
17,AT125 GRAFITO,[Gris],29999.0,10000.0,19999.0,https://www.italika.mx/motocicleta-de-trabajo-italika-at125-grafito-34006712/p
18,FT125 TS,[Rojo],27499.0,9500.0,17999.0,https://www.italika.mx/motocicleta-de-trabajo-italika-ft125-ts-roja-con-negro-34005164/p
20,FT200,[Negro],42999.0,17000.0,25999.0,https://www.italika.mx/motocicleta-de-trabajo-italika-ft200-negra-34006715/p
21,FT150,[Rojo],26499.0,7500.0,18999.0,https://www.italika.mx/motocicleta-de-trabajo-italika-ft150-roja-34006714/p
22,FT150 TS,[Negro],30999.0,11000.0,19999.0,https://www.italika.mx/motocicleta-de-trabajo-italika-ft150-ts-negro-con-verde-34005332/p
23,AT135X,[Verde],33999.0,9000.0,24999.0,https://www.italika.mx/motocicleta-de-trabajo-italika-at135x-verde-34006711/p
24,FT250 GTS CON GPS,[Azul],51999.0,17000.0,34999.0,https://www.italika.mx/motocicleta-de-trabajo-italika-ft250-gts-con-gps-azul-con-negro-34006392/p
25,FT200 GTS,[Gris],49999.0,20000.0,29999.0,https://www.italika.mx/motocicleta-de-trabajo-italika-ft200-gts-gris-con-gps-34007052/p
26,FT150 GTS GPS,[Gris],47999.0,24000.0,23999.0,https://www.italika.mx/motocicleta-italika-ft150-gts-gris-con-amarillo-con-gps-34007053/p
27,AT130 RT,[Blanco],31999.0,10000.0,21999.0,https://www.italika.mx/motocicleta-de-trabajo-italika-at130-rt-blanca-34006713/p
28,FT125 TRABAJO,[Negro],25499.0,8500.0,16999.0,https://www.italika.mx/motocicleta-de-trabajo-italika-ft125-negra-34005157/p
29,VORT-X 300R,[Azul con Gris],85999.0,23000.0,62999.0,https://www.italika.mx/motocicleta-deportiva-italika-vort-x-300r-azul-con-gris-34006484/p
30,VORT-X 250,"[Roja, Negra]",73999.0,24000.0,49999.0,https://www.italika.mx/motocicleta-deportiva-italika-vort-x-250-roja-con-negro-34005120/p
31,VORT X 300 ROJO NEGRO,"[Rojo, Negro]",79499.0,24500.0,54999.0,https://www.italika.mx/motocicleta-deportiva-italika-vort-x-300-roja-con-negro-34004912/p
32,RC200,[Gris],38499.0,11500.0,26999.0,https://www.italika.mx/motocicleta-chopper-italika-rc200-gris-34005722/p
33,Motocicleta Italika,"[Rojo, Negro, Blanco]",4000.0,400.0,3600.0,https://www.italika.mx/motocicleta-chopper-italika-tc-250-gris-34006691/p
34,RC250,[Negra],41499.0,11500.0,29999.0,https://www.italika.mx/motocicleta-chopper-italika-rc250-negra-34005813/p
35,TC 300,[Negra],58499.0,14500.0,43999.0,https://www.italika.mx/motocicleta-chopper-italika-tc-300-negra-34006362/p
36,DM150,[Blanco],38999.0,12000.0,26999.0,https://www.italika.mx/motocicleta-doble-proposito-italika-dm150-con-gps-blanca-34006888/p
37,DM300,[Dorado],54999.0,14000.0,40999.0,https://www.italika.mx/motocicleta-italika-dm300-dorado-con-gps-34006890/p
38,DM200 CON GPS,[Azul],42999.0,13000.0,29999.0,https://www.italika.mx/motocicleta-doble-proposito-italika-dm200-con-gps-azul-34006255-1300703478/p
39,FIREBIRD 300 NEGRO CON GP,[Negro],52999.0,10000.0,42999.0,https://www.italika.mx/motocicleta-italika-firebird-300-negra-con-gps-34007122/p
40,SPTFIRE 250,[Plateado],36999.0,11000.0,25999.0,https://www.italika.mx/motocicleta-cafe-racer-italika-sptfire-250-plata-34005271/p
41,F200,None,62999.0,23000.0,39999.0,https://www.italika.mx/motocicleta-italika-morbidelli-f200-34006932/p
42,NZ250,None,69999.0,20000.0,49999.0,https://www.italika.mx/motocicleta-italika-morbidelli-nz250-34006882/p
43,T250X,[Gris],59999.0,10000.0,49999.0,https://www.italika.mx/motocicleta-italika-morbidelli-t250x-gris-34007161/p
44,RT250,[Roja],50499.0,4500.0,45999.0,https://www.italika.mx/motocicleta-deportiva-italika-rt-250-con-gps-roja-34007114/p